### PR TITLE
Update titles_l_english.yml

### PR DESCRIPTION
**Pull request by Conchodebar**
Added all titles I could find. I haven't finished the catholic church titles as these don't seem ready yet.

### CODE REVIEW

**Comment by thenunnceler** [comment]
Looks good, but c_asciano has no caps in the localisation. Push a commit to this branch fixing it and I'll merge it unless Atreides says no. There's no overwrites so I don't see any risk.

**Comment by alltheatreides** [comment]
Did you use the vanilla 1.3 loc file ? It seems that some of the vanilla 1.3 title locs are not in your version.
image

Do not worry though, I can easily copy paste the title you added, thanks :)

**Comment by Conchodebar** [comment]
I used the version from the master branch, is that not correct? I'm still learning how to use github so excuse my ignorance

**Comment by alltheatreides** [comment]
> I used the version from the master branch, is that not correct? I'm still learning how to use github so excuse my ignorance

Ah nevermind you are right, I forgot about me adding that loc file, and the weird fact that github does not detect conflict fooled me, sorry !

**Comment by thenunnceler** [comment]
Shall we merge it then?

**Pull request merged**
